export { default as Footer } from "@/components/shared/layout/footer";
export { cn } from "@/lib/utils";
export { default as React, useState, useEffect } from "react";
export { Label } from "@/components/ui/label";
export { ProjectsModalWindow } from "@/components/shared/sections/ProjectsModal";
export { ServicesModalWindow } from "@/components/shared/sections/ServicesModal";
export { default as CursorShadow } from "@/components/shared/cursorShadows";
export type { Metadata } from "next";
export { Header } from "@/components/shared/layout/header";
export { Main } from "@/components/shared/layout/main";
export { SkillsModalWindow } from "@/components/shared/sections/SkillsModal";
export { AboutMeModalWindow } from "@/components/shared/sections/AboutMeModal";
export { ContactModalWindow } from "@/components/shared/sections/ContactModal";
export { GalleryModalWindow } from "@/components/shared/sections/GalleryModal";
export { ResumeModalWindow } from "@/components/shared/sections/ResumeModal";
export { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
export { Loading } from "@/components/shared/loading";